### ISSUE TITLE
トップページのYouTube関連の不備

### ISSUE THREAD

**Issue by riku1021** [yukihito-jokyu/DLab#41]
トップページにYouTubeのリンクとサムネの実装がされていない

**Comment by yukihito-jokyu** [comment]
実装しておきますか？

**Comment by riku1021** [comment]
大丈夫、俺がやるよ！

**Comment by riku1021** [comment]
あ、サムネの画像はどれにする？

**Comment by riku1021** [comment]
簡易的に作ったサムネ
![image](https://github.com/user-attachments/assets/9b19835c-6afe-4b38-8194-7e5765cb1ce7)

**Comment by yukihito-jokyu** [comment]
デザイン担当者に対応してもらいます

**Comment by nogikun** [comment]
@riku1021 
サムネについて議論したところ、添付したサムネのほうがいいのかなと思うんだけどどうでしょうか。

議論点：
- サムネイルがトップページのUIだと、マトリョーシカのようでユーザーが混乱するのではないか
- YouTubeアイコンをサムネに持ってくると埋め込み時の再生マーク（ロゴ）と被る

○ サムネ画像
![DEMO-サムネイル](https://github.com/user-attachments/assets/cb0f3b8d-40b0-4ea4-9560-0f77cae92bb9)

○ 埋め込み時のプレビュー（動画再生前）
![image](https://github.com/user-attachments/assets/16de3cf0-66b9-440f-b9d8-5c81dc2bc222)

**Comment by riku1021** [comment]
確かに、めっちゃいいと思う！

**Comment by nogikun** [comment]
ありがとう！
実装についてやけど埋め込みだけやから、俺がやっとこうか？
それか今作業してる人にお願いした方がいいかな？

**Comment by riku1021** [comment]
いま作業してる人ってほどはいないからお願いしような？
いまmainが最新になっていなくて、ややこしくなってるからmainが最新なったらまた連絡する！

**Comment by yukihito-jokyu** [comment]
僕がやっときます

**Comment by yukihito-jokyu** [comment]
解決したので閉じる
