### ISSUE TITLE
プロフィールの参加プロジェクトの不備

### ISSUE THREAD

**Issue by riku1021** [yukihito-jokyu/DLab#42]
プロフィールページにて、自身が参加している強化学習のプロジェクト及びその順位が表示されていない

**Comment by yukihito-jokyu** [comment]
現在firebaseのjoin_projectの部分から参照し、表示しています。
join_projectには、プロジェクト参加時にプロジェクト名が追加されます。
強化学習は初期でプロジェクトに参加しているため、そのような動作が適用されていません。
実装するならば、ユーザー登録時(firebaseにuserデータを作成時)にjoin_projectに強化学習のプロジェクトを追加するのがベストだと思います。

**Comment by riku1021** [comment]
お願いしたいです。（不要と判断するのであれば対処しなくても）

**Comment by yukihito-jokyu** [comment]
はい

**Comment by yukihito-jokyu** [comment]
解決したので閉じる
