### ISSUE TITLE
プロップスの使用方法による保守性の低下

### ISSUE THREAD

**Issue by riku1021** [yukihito-jokyu/DLab#47]
・コンポーネントをプロップスで渡していることにより、保守性が低下してしまっている。
⇒ファイル内丈夫でimportに変更
・const ○○ = props.○○;、const △△ = props.△△;、const ✕✕ = props.✕✕;のような定義はコードが冗長になっている。
⇒function コンポーネント({})内に直接定義した方が良い。

**Comment by yukihito-jokyu** [comment]
お願いします

**Comment by riku1021** [comment]
了解、個人で対処するには膨大なので対処しない方向にします。
